// <autogenerated/>

namespace Kistl.App.GUI
{
    using System;
    using System.Collections.Generic;

    using Kistl.API;

    /// <summary>
    /// The ControlKind specifies the toolkit-independent kind or type of control that should display a given Presentable.
    /// </summary>
    public interface ControlKind : IDataObject, Kistl.App.Base.IExportable 
    {

        /// <summary>
        /// The name of this ControlKind
        /// </summary>
		string Name {
			get;
			set;
		}
    }
}