// <autogenerated/>

namespace Kistl.App.GUI
{
    using System;
    using System.Collections.Generic;

    using Kistl.API;

    /// <summary>
    /// A textbox-like control
    /// </summary>
    public interface TextboxKind : Kistl.App.GUI.ControlKind 
    {

    }
}