CREATE ROLE zbox LOGIN
  ENCRYPTED PASSWORD '....'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE DATABASE zbox
  WITH OWNER = zbox
       ENCODING = 'UTF8'
       CONNECTION LIMIT = -1;

GRANT CONNECT, TEMPORARY ON DATABASE zbox TO public;
GRANT ALL ON DATABASE zbox TO zbox;

DROP SCHEMA public;

CREATE SCHEMA dbo
  AUTHORIZATION zbox;
GRANT ALL ON SCHEMA dbo TO zbox;
