//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zetbox.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zetbox.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapping Assembly Resolver.
        /// </summary>
        public static string Startup_AssemblyResolver {
            get {
                return ResourceManager.GetString("Startup_AssemblyResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting credentials.
        /// </summary>
        public static string Startup_EnsuringCredentials {
            get {
                return ResourceManager.GetString("Startup_EnsuringCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init application.
        /// </summary>
        public static string Startup_InitApp {
            get {
                return ResourceManager.GetString("Startup_InitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Launcher.
        /// </summary>
        public static string Startup_Launcher {
            get {
                return ResourceManager.GetString("Startup_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zetbox is starting....
        /// </summary>
        public static string Startup_Message {
            get {
                return ResourceManager.GetString("Startup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No server start required.
        /// </summary>
        public static string Startup_NoServerStart {
            get {
                return ResourceManager.GetString("Startup_NoServerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Server.
        /// </summary>
        public static string Startup_Server {
            get {
                return ResourceManager.GetString("Startup_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorised.
        /// </summary>
        public static string Uncategorised {
            get {
                return ResourceManager.GetString("Uncategorised", resourceCulture);
            }
        }
    }
}
